const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const Ticket = require('../models/Ticket');

const SEED_TICKETS = [
  {
    name: 'Hapoel Beer Sheva vs Maccabi Haifa',
    category: 'Sports',
    date: new Date('2026-03-22T00:00:00.000Z'),
    venue: 'Turner Stadium',
    city: 'Beer Sheva',
    price: 100,
    originalPrice: 120,
    views: 312,
    available: 15,
    verified: true,
    instant: true,
    section: 'East Stand',
    row: '3',
    sellerName: 'Yossi M.',
    sellerRating: 4.8,
    sellerReviews: 67,
    sellerSince: '2021',
    description: 'Great seats at Turner Stadium for the Hapoel Beer Sheva home game. East Stand, Row 3. Digital tickets transferred instantly.',
  },
  {
    name: 'Gad Elbaz Stand-Up Special',
    category: 'Comedy',
    date: new Date('2026-03-29T00:00:00.000Z'),
    venue: 'Zappa Herzliya',
    city: 'Herzliya',
    price: 150,
    originalPrice: 180,
    views: 134,
    available: 2,
    verified: true,
    instant: false,
    section: 'Floor',
    row: '2',
    sellerName: 'Dana K.',
    sellerRating: 4.7,
    sellerReviews: 56,
    sellerSince: '2023',
    description: 'Great floor seats for the Gad Elbaz stand-up special. Row 2, very close to the stage. Digital barcode tickets.',
  },
  {
    name: 'Habima Theater – The Dybbuk',
    category: 'Theater',
    date: new Date('2026-03-08T00:00:00.000Z'),
    venue: 'Habima National Theatre',
    city: 'Tel Aviv',
    price: 250,
    originalPrice: 260,
    views: 89,
    available: 22,
    verified: true,
    instant: true,
    section: 'Stalls',
    row: 'C',
    sellerName: 'Avi S.',
    sellerRating: 5.0,
    sellerReviews: 33,
    sellerSince: '2021',
    description: 'Premium stall seats for the Habima production of The Dybbuk. Row C, center. Classic Israeli theater experience.',
  },
  {
    name: 'InDNegev Festival 2026',
    category: 'Festival',
    date: new Date('2026-04-03T00:00:00.000Z'),
    venue: 'Negev Desert',
    city: 'Beer Sheva',
    price: 320,
    originalPrice: 390,
    views: 541,
    available: 6,
    verified: true,
    instant: false,
    section: 'General',
    row: '',
    sellerName: 'Michal L.',
    sellerRating: 4.8,
    sellerReviews: 89,
    sellerSince: '2022',
    description: "Weekend festival pass for InDNegev 2026. One of Israel's biggest outdoor festivals. Camping access included.",
  },
  {
    name: 'Maccabi Tel Aviv vs Real Madrid – Euroleague',
    category: 'Sports',
    date: new Date('2026-03-15T00:00:00.000Z'),
    venue: 'Menora Mivtachim Arena',
    city: 'Tel Aviv',
    price: 380,
    originalPrice: 450,
    views: 820,
    available: 4,
    verified: true,
    instant: true,
    section: 'VIP A',
    row: '3',
    sellerName: 'Roni B.',
    sellerRating: 4.9,
    sellerReviews: 201,
    sellerSince: '2020',
    description: 'Euroleague matchup — Maccabi TLV vs Real Madrid. VIP A, Row 3. Electric atmosphere guaranteed. Digital tickets.',
  },
  {
    name: "Idan Raichel – Live at the Sultan's Pool",
    category: 'Concert',
    date: new Date('2026-05-10T00:00:00.000Z'),
    venue: "Sultan's Pool",
    city: 'Jerusalem',
    price: 280,
    originalPrice: 310,
    views: 673,
    available: 9,
    verified: true,
    instant: true,
    section: 'Premium',
    row: '5',
    sellerName: 'Shira T.',
    sellerRating: 4.9,
    sellerReviews: 112,
    sellerSince: '2022',
    description: "One of Israel's most iconic open-air venues. Premium seating with stunning views of the Old City. Digital tickets.",
  },
  {
    name: 'Eyal Golan Live Tour',
    category: 'Concert',
    date: new Date('2026-04-18T00:00:00.000Z'),
    venue: 'Yarkon Park',
    city: 'Tel Aviv',
    price: 220,
    originalPrice: 250,
    views: 445,
    available: 18,
    verified: true,
    instant: false,
    section: 'Lawn',
    row: '',
    sellerName: 'Noa H.',
    sellerRating: 4.6,
    sellerReviews: 45,
    sellerSince: '2023',
    description: 'Open-air concert in Yarkon Park. Lawn access, great atmosphere. One of the biggest Israeli pop acts live.',
  },
  {
    name: 'Israel vs Portugal – World Cup Qualifier',
    category: 'Sports',
    date: new Date('2026-06-07T00:00:00.000Z'),
    venue: 'Teddy Stadium',
    city: 'Jerusalem',
    price: 140,
    originalPrice: 140,
    views: 1200,
    available: 30,
    verified: true,
    instant: true,
    section: 'North Stand',
    row: '22',
    sellerName: 'Tal R.',
    sellerRating: 4.9,
    sellerReviews: 188,
    sellerSince: '2020',
    description: 'World Cup qualifying match at Teddy Stadium. North Stand, Row 22. High demand — grab yours before they sell out.',
  },
  {
    name: 'Stand-Up Night at Haifa',
    category: 'Comedy',
    date: new Date('2026-04-25T00:00:00.000Z'),
    venue: 'Haifa Auditorium',
    city: 'Haifa',
    price: 80,
    originalPrice: 90,
    views: 67,
    available: 3,
    verified: false,
    instant: false,
    section: 'Balcony',
    row: '1',
    sellerName: 'Gal M.',
    sellerRating: 4.2,
    sellerReviews: 12,
    sellerSince: '2024',
    description: 'Multi-comedian stand-up night at Haifa Auditorium. Balcony seats, Row 1. Fun evening guaranteed.',
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI as string, { serverSelectionTimeoutMS: 5000 });
  console.log('Connected to MongoDB');

  await Ticket.deleteMany({});
  console.log('Cleared existing tickets');

  const result = await Ticket.insertMany(SEED_TICKETS);
  console.log(`Seeded ${result.length} tickets`);

  await mongoose.disconnect();
  console.log('Done');
}

seed().catch(err => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
